service:
  name: serverless-lambda-node
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '>=1.0.0 <2.0.0'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  handler:
    handler: handler.handler
    events:
      - http:
          method: get
          path: /
      # - http: ANY /
      #   cors:
      #     origin: '*'
      # - http: ANY {proxy+}
      #   cors:
      #     origin: '*'
